variable "region" {}
variable "project_name" {}
variable "environment" {}
variable "Pubsubaz1" {}
variable "Pubsubaz2" {}
variable "vpcigw" {}
variable "vpc_id" {}
variable "Privappsubaz1_id" {}
variable "Privappsubaz2_id" {}
variable "Privdbsubaz1_id" {}
variable "Privdbsubaz2_id" {}